/// This file is auto generated by the build.rs file.
use faust_types::ParamIndex;
#[derive(Params)]
struct GainFaustNihPlugParams {
    #[id = "CutOff"]
    cutoff: FloatParam,
    #[id = "Resonance"]
    resonance: FloatParam
}

impl Default for GainFaustNihPlugParams {
    fn default() -> Self {
        Self {
            cutoff: FloatParam::new("CutOff", 1.0, FloatRange::Linear { min: 0.0, max: 1.0}),
            resonance: FloatParam::new("Resonance", 1.0, FloatRange::Linear { min: 0.0, max: 2.0})
        }
    }
}

pub const CUTOFF_PI: ParamIndex = ParamIndex(0);
pub const RESONANCE_PI: ParamIndex = ParamIndex(1);
